" @ERR []
function! Foo()
	let self = 1
	return self
endfunction

